"""empty message

Revision ID: 8151726c14ec
Revises: f801a5bbff24
Create Date: 2024-01-03 14:55:44.180086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8151726c14ec'
down_revision = 'f801a5bbff24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leilao', schema=None) as batch_op:
        batch_op.alter_column('qtd_produtos',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leilao', schema=None) as batch_op:
        batch_op.alter_column('qtd_produtos',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
